### ISSUE TITLE
please add a redme file

### ISSUE THREAD

**Issue by vinayakumarr** [albertbup/deep-belief-network#1]
I have seen your code. It's nice but the classification example what you had given ...is that works for any dimensionality data set...which means i have data which is of size 1000 * 20 - 19 features and 1 class label(10 classes) and test data set has 100*20 - 19 features and 1 class label (15 classes). What are all the changes i need to be done to make it work..

**Comment by albertbup** [comment]
Implementation follows the scikit-learn API. In short, there are two basic methods: fit and predict. Both expect two parameters, "X" being the data as numpy ndarray of (n_samples, n_features) and "y" the labels as numpy array of (n_samples, ). I recommend you to read the scikit-learn [tutorial](http://scikit-learn.org/stable/tutorial/basic/tutorial.html). Regards.
