### ISSUE TITLE
Gaussian Bernoulli RBM

### ISSUE THREAD

**Issue by nirvana1122** [albertbup/deep-belief-network#14]
This is the best working library I could find for DBN. I am a newbie, and wondering if I can use it for GBRBM? Any help will be appreciated.

Thanks,

**Comment by lhr5687** [comment]
sorry ,I am also a newer


 
From: nirvana1122
Date: 2017-05-24 07:21
To: albertbup/deep-belief-network
CC: Subscribed
Subject: [albertbup/deep-belief-network] Gaussian Bernoulli RBM (#14)
This is the best working library I could find for DBN. I am a newbie, and wondering if I can use ti for GBRBM? Any help will be appreciated.
Thanks,

**Comment by nirvana1122** [comment]
Thank you!

**Comment by albertbup** [comment]
Hi,
The model you suggest is not implemented. I encourage you to do it, feel free to do a pull request when completed.

Best.

**Comment by nirvana1122** [comment]
I will give it a try. I need to create another class GBRBM similar to BinaryRBM. I found another library PDNN which has the implementation I am looking for, but this library is much cleaner and nicer than PDNN. I will try to implement PDNN logic for Gauss-Bernaulli using your framework.
