### ISSUE TITLE
Issue on runing demo examples

### ISSUE THREAD

**Issue by skx300** [albertbup/deep-belief-network#16]
Run classification_demo.py and regression_demo. I have the following error:
**No module named 'dbn.tensorflow'**

OS: windows 7
Python: 3.5.2
tensorflow: 1.0.1

**Comment by albertbup** [comment]
Hi,
Have you installed the project with pip? It is explained in the [readme](https://github.com/albertbup/deep-belief-network/blob/master/README.md)

**Comment by skx300** [comment]
Hi,

For the installation:
I can't use pip install git+git://github.com/albertbup/deep-belief-network.git as the VPN setting.
I just use **pip setup.py install** instead. Is there anything wrong with this?

Your second option works!
Thank you.

**Comment by abdulwajid725** [comment]
Hi,
Getting this error even after intalling dbn using "git+git://github.com/albertbup/deep-belief-network.git"

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-60-8737540f6f0c> in <module>
     24 from sklearn.preprocessing import MinMaxScaler
     25 
---> 26 from dbn import SupervisedDBNClassification

ModuleNotFoundError: No module named 'dbn'

Please look into it.

**Comment by muhaldiriz** [comment]
hi, sorry. i've got trouble for the dbn library, but i need this to solve ASAP, can i get ur email or something to asking about this things?
