### ISSUE TITLE
getting unhashable type 'numpy.ndarray' error

### ISSUE THREAD

**Issue by vinayakumarr** [albertbup/deep-belief-network#2]
after 20 epochs of RBM reconstruction, generates the error

**Comment by albertbup** [comment]
What input are you passing to the network? Please, refer to #1 to be sure you are giving the right inputs.

**Comment by 313hemant313** [comment]
Hello.. Facing similar error

Tried to follow scikit-learn tutorial still no luck.
Please help me resolve this issue.

Input details:
![image](https://user-images.githubusercontent.com/61142369/83950327-84a87b80-a847-11ea-95b3-59dbdda58b9d.png)

Error:
![image](https://user-images.githubusercontent.com/61142369/83950244-e4525700-a846-11ea-9319-b3d72a8cce6a.png)

Regards

**Comment by tugbakara** [comment]
Hi @vinayakumarr , I have a data with 32x32 images and thei corresponding labels are şn the sahpe of 32x32 matrix, each pixel has a label but totally 8 class I have, and I got the same error, how did you solve that issue, I have tried to reshape my datas but another error raises, here is the actual data shapes of my dataset:

```
X_new shape: (13702, 32, 32)
y_new shape: (13702, 32, 32)

```
X_new for the datas and y_new for the labels.
