### ISSUE TITLE
Is momentum and weight decay implemented? [Short Answer: No]

### ISSUE THREAD

**Issue by jomangy** [albertbup/deep-belief-network#20]
Hi,
just want to ask if: **momentum** and **weight decay** are implemented,
and/or someone knows how to easily integrate it into the code.

If not, is it possible that I’ll try to do it myself and add it to your code? (pull request)

Thanks! (nice package :+1:  )

**Comment by albertbup** [comment]
Hey,

They're not implemented. Feel free to try it

**Comment by jomangy** [comment]
Thanks, will try it.
