### ISSUE TITLE
Question regarding hidden_layers_structure 

### ISSUE THREAD

**Issue by eragonngo** [albertbup/deep-belief-network#21]
Dear albertbup, 

First of all, thank you so much for implementing DBN into Python with lots of example from logistic regression, linear regression. Also, I have a question with your sample code, which is:  `hidden_layers_structure = [256,256]`, does that mean this DBN has 2 hidden layers with 256 neurons in each hidden layer ? Because I believe a standard DBN usually has 3 hidden layers (with hidden layer 1 as RBM). Hope you can help with my confusion.

Thank you for your time, 

Sincerely,

**Comment by albertbup** [comment]
Hey,
> ...does that mean this DBN has 2 hidden layers with 256 neurons in each hidden layer ? 

Exactly.

> Because I believe a standard DBN usually has 3 hidden layers (with hidden layer 1 as RBM)

DBN is just a composition of an arbitrary number of stacked RBM's, find out more [here](http://www.scholarpedia.org/article/Deep_belief_nets).

Best regards,
