### ISSUE TITLE
Diffrent dataset for backpropagation of the “ANN”

### ISSUE THREAD

**Issue by Ahone91** [albertbup/deep-belief-network#29]
Hi, thanks for really good code!

I would like to use the deep-belief-network for regression. 

My problem is that I would like to use a different dataset for the last backpropagation of the “ANN” then for initial training of the RBM. Is that possible?

I’m trying to use the deep-belief-network for soft sensor modelling in chemical plants. Found some interesting academic publications where they have used it with great results.

Thanks in advance,

Have a good day,

Best regards
Lukas

**Comment by albertbup** [comment]
Hi,

Yes, you can although it's not clear how to do it, I think I need to make that part easier. But here it is:
```python
dbn = SupervisedDBNRegression(...)

# Do pre-training for RBM stack
dbn.pre_train(X_1)

# Fine-tune with backprop
dbn.fit(X_2, y, pre_train=False)
```
Hope it helps!
