### ISSUE TITLE
RuntimeWarning - Result in NaN - Python 3.5

### ISSUE THREAD

**Issue by sinoforever** [albertbup/deep-belief-network#3]
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dbn/models.py:127: RuntimeWarning: invalid value encountered in subtract
  delta_W = np.outer(h_0, v_0) - np.outer(h_k, v_k)
/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dbn/models.py:129: RuntimeWarning: invalid value encountered in subtract
  delta_c = h_0 - h_k

Not sure if it's Python 3's issue, I've fixed the errors that prevents the programs from running in python3, like prints and maps, but not sure what these are about. Are they not the same in 2.7 and 3.5?

**Comment by albertbup** [comment]
Hi sinoforever, 
I haven't tried the code with Python 3.5 but I recommend you to check 2 things before going into Python version issues:
1. Check your input data does not contain any NaN value.
2. Make sure your data is normalized either by scaling features to range [0, 1] or zero mean and unit variance, that will avoid possible overflows (so NaN values) when using _exp_ function with large numbers.

Hope that helps.
