### ISSUE TITLE
dbn 

### ISSUE THREAD

**Issue by sanjanasri** [albertbup/deep-belief-network#33]
I've been using your dbn for my project. I'd like to first appreciate your amazing work. I am trying to develop something like the image shown below 

![dbn](https://user-images.githubusercontent.com/13214774/43442442-92fc2be2-94bb-11e8-8f8c-ef25cf3850cd.png)

The question I've come across with is

a) I developed separate encoders for two languages and a joint layer using SupervisedDBNClassification()
b) How can I get the weights at each layer
c) How do i do back propagation all together as a single network

Since I am newbie to Tensor flow and Python I dunno how to alter the source code.
Any help would be appreciated.

**Comment by albertbup** [comment]
Hi, thanks for your comments.

> How can I get the weights at each layer

Look at BaseTensorFlowModel.to_dict() method. In the second statement weights are saved in a python dict.

> How do i do back propagation all together as a single network

Current design does not support network branching. 

> Since I am newbie to Tensor flow and Python I dunno how to alter the source code.

I suggest you to use other tools for what you want to achieve e.g. Keras, PyTorch etc. They are easy to work with and support complex network architectures out-of-the-box.

Cheers.
