### ISSUE TITLE
Hidden units number_ deep-belief-network for regression

### ISSUE THREAD

**Issue by naloui1** [albertbup/deep-belief-network#34]
Hi, thanks for really good code!
I would like to use the deep-belief-network for regression. But, when I see your code, I can see that the number of hidden layers (hidden_layers_structure), the learning rates (learning_rate_rbm,          learning_rate), epochs'number (n_epochs_rbm, n_iter_backprop), batch size( batch_size) and activation function are settable. However, this is not the case of the number of hidden units. 
How is it set please? 
Thank you
Best regards

**Comment by albertbup** [comment]
Hi, 
thanks for your comments.

Let me be practical: say hidden_layers_structure=[256, 128], what that means is that your network will have 2 hidden layers, the first one with 256 neurons and the second one with 128. That's the way how you can control the number of hidden units.

Best regards

**Comment by mahagnyana** [comment]
how about the visible unit albert?
