### ISSUE TITLE
How to add new optimizer

### ISSUE THREAD

**Issue by starfriend10** [albertbup/deep-belief-network#38]
First, thanks for creating such a wonderful package!
I am investigating if it is possible to use customized optimizer, such as adam? There are code for adam available, but the question is how to adapt it into the DBN code? Advice and help are very welcome. Thanks.
(I changed my original question, and I think this is what I want to know)

**Comment by starfriend10** [comment]
I already added an optimizer by myself, so you can close this question.

**Comment by dangmanhtruong1995** [comment]
Hi, I am also interested in using Adams optimizer for DBN. Can you share the code ? Thank you very much
