### ISSUE TITLE
How to use albertbup with CSV file?

### ISSUE THREAD

**Issue by dinasaif** [albertbup/deep-belief-network#4]
I have CSV file with binary features and 2 class labels (0,1), I want to use deep belief network with my file , how to do that?

**Comment by albertbup** [comment]
Hi,
Read that csv file either with numpy or built-in python csv module. For the later you will have to convert it into a numpy array. In any case you want a numpy arrsy of shape (nb_samples, nb_features). Same for labels, which shape would be (nb_samples, nb_classes). 
I suggest you to run the examples to get a better idea.

Best regards.

**Comment by dinasaif** [comment]
Thanks for reply ,
Can you write it in examples in your project , I'm new in python , I think lots of people need deep belief network with CSV , you will help us .
Thanks

**Comment by aszhanghuali** [comment]
@dinasaif Hi！
Did you run the repo successfully?And what dataset did you use?
Looking forward to your reply!
