### ISSUE TITLE
No module called Tensorflow

### ISSUE THREAD

**Issue by skjerns** [albertbup/deep-belief-network#5]
When I want to run the sample code, it always tells me

ImportError: No module named tensorflow

Tensorflow is installed and runningh though!

**Comment by albertbup** [comment]
Hello,
It seems your error is not related with my code but  your tensorflow installation. I suggest you to:
Make sure you have correctly installed TensorFlow (https://www.tensorflow.org/install). Also If you have installed installed tensorflow within a virtualenv make sure this is activated when you run the sample code.

Regards.

**Comment by skx300** [comment]
I have the same error too. It seems like the importing error.
