### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'Session'

### ISSUE THREAD

**Issue by haithamalshari** [albertbup/deep-belief-network#55]
When I import the library I got this error:
AttributeError: module 'tensorflow' has no attribute 'Session'

after searching about it I found the problem in the model file:
import tensorflow as tf
sess = tf.Session()

tensorflow 2 and above remove the session() from tf.Session() to tf.compat.v1.Session()

**Comment by albertbup** [comment]
Hi,
Tensorflow 2 is not supported. I've just updated ```requirements.txt``` file to stick the project to version 1.5. Please, git pull or update the package with pip.

Btw, I encourage you to make a pull request with changes supporting tensorflow version 2.

Regards
