### ISSUE TITLE
Doesn't work with GPU

### ISSUE THREAD

**Issue by nirvana1122** [albertbup/deep-belief-network#7]
Hi - the code isn't working with GPU. I see that tensor flow gets initialized, but the GPU usage stays lower than 5%. I am running unsupervised_demo.py

**Comment by albertbup** [comment]
Hey,
your problem is in the import, so models using TensorFlow are located in tensorflow module. Thus change the import as:
`from dbn.models import UnsupervisedDBN `
for
`from dbn.tensorflow import UnsupervisedDBN `

I think I will add a comment in unsupervised_demo.py explaining it.

Best,
Albert

**Comment by nirvana1122** [comment]
Thank you for the prompt reply. I am importing UnsupervisedDBN from dbn.tensorflow , just as you described in unsupervised_demo.py . I can see that tensor flow allocates the memory but the GPU usage stays low after that.

**Comment by albertbup** [comment]
Hey,

According to [gpu tensorflow documentation](https://www.tensorflow.org/tutorials/using_gpu), they say gpu is given more priority than cpu, so if your machine has a gpu tensorflow will use it first.  Also check you have properly installed tensorflow for gpu  [here](https://www.tensorflow.org/install/install_linux). If the above doesn't work then try to force tensorflow to use your gpu (check the first link).

Best,
Albert.

**Comment by fishinbox** [comment]
GPU is used during fine-tuning stage. However, GPU is not used during pretraining stage.
