### ISSUE TITLE
How can I save your RBM network?

### ISSUE THREAD

**Issue by pknam** [albertbup/deep-belief-network#9]
How can I save your network using `tf.train.Saver`?
I'm using `SupervisedDBNClassification` classifier.

And if possible, can you add a `Save` method?
thanks

**Comment by albertbup** [comment]
Hey,
now Tensorflow-based models can be saved. Check the [example](https://github.com/albertbup/deep-belief-network/blob/master/examples/save_demo.py)

Enjoy,
Albert.
